version: '3.8'

services:
  simulator:
    image: eufs_sim
    build:
      context: .
      args:
        - PLATFORM=${PLATFORM}
    environment:
      - DISPLAY=docker.for.mac.host.internal:0 
    volumes:
      - "~/.Xauthority:/root/.Xauthority"
    privileged: true
    network_mode: host
    entrypoint: ["/bin/bash", "-c", "/start_simulator.sh"]
